license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="zhaiji"
description='''
This mod adds Elaina's broom from the anime "The Journey of Elaina"
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sophisticatedbackpacks"
    type="optional"
    versionRange="[3.25,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    ordering="AFTER"
    side="BOTH"
